### ISSUE TITLE
GIMME_ARCH arm64 does not set GOARCH to arm64

### ISSUE THREAD

**Issue by csandanov** [travis-ci/gimme#154]
```yml
...
env:
  matrix:
    - GIMME_OS=linux GIMME_ARCH=arm
    - GIMME_OS=linux GIMME_ARCH=arm64
...
```
`GIMME_ARCH=arm` works fine and sets `GOARCH=arm` unlike `arm64`. I don't know, maybe it's just not supported? Could not find a list of supported `GIMME_ARCH`s.
