### ISSUE TITLE
Go 1.12.2 gcc failed / unrecognized relocation

### ISSUE THREAD

**Issue by adamdecaf** [travis-ci/gimme#174]
I noticed several of my projects are failing their Linux builds and it seems gimmie is the cause. 

```
$ go test ./... -race -coverprofile=coverage.txt -covermode=atomic
# github.com/moov-io/paygate.test
/home/travis/.gimme/versions/go1.12.2.linux.amd64/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-006285876/000006.o: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```

Here's an example build: https://travis-ci.com/moov-io/paygate/jobs/190895451 and [config file](https://github.com/moov-io/paygate/blob/master/.travis.yml) (pasted below as well). 

<details>
<summary>.travis.yml</summary>

```yaml
language: go
sudo: true
services:
  - docker
env:
  matrix:
    - GO111MODULE=auto
matrix:
  include:
    - os: linux
      go: 1.12.x
      cache:
        directories:
          - "/home/travis/.cache/go-build" # GOCACHE
    - os: osx
      go: 1.12.x
      cache:
        directories:
          - "/Users/travis/Library/Caches/go-build" # GOCACHE
before_install:
  - go get -u github.com/client9/misspell/cmd/misspell
  - go get -u golang.org/x/lint/golint
  - go get github.com/fzipp/gocyclo
  - go get -u honnef.co/go/tools/cmd/megacheck
  - go get golang.org/x/tools/cmd/cover
before_script:
  - GOFILES=$(find . -type f -name '*.go' | grep -v vendor)
script:
  # Just check gofmt on linux, it's the fastest builder
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -z $(gofmt -s -l $GOFILES); fi
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  - misspell -error -locale US $GOFILES
  - gocyclo -over 25 $GOFILES
  - golint -set_exit_status $GOFILES
  - megacheck ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - make docker
before_deploy:
  - make dist
deploy:
  provider: releases
  api_key:
    secure: JaZPNf9Er+wCWwqgfGQowRL8/FZ8FZ4I1CI65ZI16j0HuSxUSdl4ygOeF8SNZ3UMecC8OlRhyuyxIEfoFpxjKvKL7fNyCJCfDGIY/icqmbNoTZitaJwF2QkYQ97U8gtAi1951kcI5A118Ynd/6jKCyYjEhhnlVMJwVuk723A0qWgRFzVekoMWuc+wo4diCrAjVXKvwivJn2CpAYkMlTpQTZgAQm4XbnHtnoB/sR7uDmJpeiOjShfFtYfOTsrqINJND+3bdPTySkPO4MaZ8yB+esdF69URSWOsGhdJf7O0m+494mQjeMdmqyAj0XD7D6NW0253N7oh2ikSa1Cq0xJ1zvUFMnvu3DVlQkEmF+G9pB+C+x0lbxmhO4UelX9wETnohRjZvxqQACZhZrTsh4B+AdGKM1kZkBXpm38aT0U80w7ICczg952is04ZX1YBXXl4m3tWd6MlN3hEdzDaPMj57Rg9v+SyslCLYPQfi0uP1fSc/gjYHogY8UvSLI8R+H7ri71pe/ACoJ/tew6Z6oKyHAigivTBXcGWcDOSWP2DfLBdSrqsKtnDJPiieyINsqzTY1xsHggSTj7bW4PGetg7Yudmf1LB4/A5W5cOTSdhMB4NZh14dbASL/l7eHeZhXGng3XWLX1dBu3h4dsTIm+Mnj/YCbYXFprk4IHzLjADYM=
  file_glob: true
  file:
    - bin/paygate-*
  on:
    repo: moov-io/paygate
    tags: true
    go: 1.12.x
after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make release-push
```

</details>
