### ISSUE TITLE
Cross compilation is not working

### ISSUE THREAD

**Issue by mavlyutov** [travis-ci/gimme#42]
Hi!

I am trying to use gimme cross compilation feature by defining `GIMME_OS` env var.
But it seems windows and darwin builds are not affected =(
In the build log of windows branch one could find: `GOOS=linux`
moreover, go 1.6 with `GIMME_OS=windows` throws an error

```
$ eval "$(gimme 1.6)"
error: Missing bootstrap installation
error: Unable to compile go from git clone
error: Missing bootstrap installation
error: Unable to compile go from git clone
I don't have any idea what to do with '1.6'.
  (using type 'auto')
```

here's my config file:

```
language: go

go:
  - 1.6

env:
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=darwin GIMME_ARCH=amd64
  - GIMME_OS=windows GIMME_ARCH=amd64

install:
  - go get -d -v ./...

script:
  - go build -v

deploy:
  provider: releases
  api_key:
    secure: "Fx2Kx0KP ** SNIP ** DqGtN4Mqns="
  file: golagraphite_*
  skip_cleanup: true
  on:
    tags: true
```

build: https://travis-ci.org/mavlyutov/golagraphite/jobs/122741090
